version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      entrypoint: ["/entrypoint.sh"]
    image: simkerma-pnj
    container_name: simkerma-pnj-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "8000:80"
    networks:
      - simkerma-network

  db:
    image: postgres:13
    container_name: simkerma-pnj-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata-simkerma:/var/lib/postgresql/data
    networks:
      - simkerma-network

  redis:
    image: redis:alpine
    container_name: simkerma-pnj-redis
    restart: unless-stopped
    networks:
      - simkerma-network

  memcached:
    image: memcached:alpine
    container_name: simkerma-pnj-memcached
    restart: unless-stopped
    networks:
      - simkerma-network

networks:
  simkerma-network:
    driver: bridge

volumes:
  dbdata-simkerma:
    driver: local
