version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: simkerma
    container_name: simkerma-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "8000:80"
    environment:
      TZ: ${APP_TIMEZONE:-Asia/Jakarta}
    networks:
      - simkerma

  db:
    image: postgres:13
    container_name: simkerma-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: ${APP_TIMEZONE:-Asia/Jakarta}
    volumes:
      - dbdata-simkerma:/var/lib/postgresql/data
    networks:
      - simkerma

  redis:
    image: redis:alpine
    container_name: simkerma-redis
    restart: unless-stopped
    networks:
      - simkerma

  memcached:
    image: memcached:alpine
    container_name: simkerma-memcached
    restart: unless-stopped
    networks:
      - simkerma

networks:
  simkerma:
    driver: bridge

volumes:
  dbdata-simkerma:
    driver: local
